### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Hensel3** [Peeples-Lab/HLTDNN#1]
ValueError: With n_samples=1, test_size=None and train_size=0.5, the resulting train set will be empty. Adjust any of the aforementioned parameters.
how to address this question?

**Comment by jarinritu** [comment]
@Hensel3 It seems you're facing a 'ValueError' due to having only one sample (n_samples=1) while trying to split it into training and testing sets with a 50% train_size

Before running your code, please ensure you've followed these steps:
1. **Download the Dataset:** Make sure you have downloaded the dataset correctly. Double-check the source of your data to confirm that it contains more than one sample. 
2. **Data Preprocessing:** Verify that you've applied data preprocessing by executing 'Get_preprocessed_data.py'

If, after verifying the above steps, you still encounter the same error, it would be helpful to provide more information about where this error is occurring, such as the filename or a specific section of your code. This context will allow for more precise assistance in resolving the issue.

**Comment by Hensel3** [comment]
I have downloaded the data set correctly and preprocessed it, but the problem still occurs.Below is the complete error information:
Starting Experiments...
Number of parameters: 11144
Initializing Datasets and Dataloaders...
Traceback (most recent call last):
  File "C:/Users/A/Desktop/HLTDNN-master/demo.py", line 200, in <module>
    main(params)
  File "C:/Users/A/Desktop/HLTDNN-master/demo.py", line 101, in main
    dataloaders_dict = Prepare_DataLoaders(Params, split)
  File "C:\Users\A\Desktop\HLTDNN-master\Prepare_Data.py", line 35, in Prepare_DataLoaders
    train_dataset = DeepShipSegments(data_dir, partition='train', transform = data_transforms['train'])
  File "C:\Users\A\Desktop\HLTDNN-master\Datasets\DeepShipSegments.py", line 43, in __init__
    subfolders_test, subfolders_val = train_test_split(subfolders_test_val, 
  File "C:\Epan\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "C:\Epan\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=1, test_size=None and train_size=0.5, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by jarinritu** [comment]
@Hensel3 Please make the following adjustment in the code [demo.py line 101]: remove the 'split' parameter and use this line instead:

dataloaders_dict = Prepare_DataLoaders(Params)

Our code base has been recently updated, so it would be helpful to pull or download the latest repository if you haven't already. If the issue persists, feel free to reach out for further assistance.

**Comment by Hensel3** [comment]
Hello, I just downloaded the latest code you uploaded, and the following problems occurred when installing requirements:
(venv) C:\Users\A\Desktop\HLTDNN-master2>pip install skimage==0.0
Collecting skimage==0.0
  Using cached skimage-0.0.tar.gz (757 bytes)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
     
      *** Please install the `scikit-image` package (instead of `skimage`) ***
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
How should this dependency be installed

**Comment by jarinritu** [comment]
@Hensel3 To install the correct package, you can use the following command:
pip install scikit-image

**Comment by Hensel3** [comment]
May I add your contact information? I still had some difficulties

**Comment by jarinritu** [comment]
@Hensel3 you can reach out to me at jarin.ritu@tamu.edu
