### ISSUE TITLE
the division of the dataset folder

### ISSUE THREAD

**Issue by yanggg12321** [Peeples-Lab/HLTDNN#5]
I'm not sure which .wav files are present in the Deepship/Cargo/Cargo1 folder. Is this classification based on the ship names in the cargometafile? For example, are all the .wav files with the ship name "SEASPAN SWIFT" placed in Cargo1?  Look forward to your response， thank you !

**Comment by jarinritu** [comment]
I appreciate you getting in touch.
All of the files are organized in the meta file according to their class IDs and dates. In the dataset folders, the folder names are all also in the format of date-id . All the .wav files with the ship name "SEASPAN SWIFT" will not be included in Cargo 1. The folders [Cargo1, Cargo2,...,CargoN] are saved as per their date-id.

**Comment by yanggg12321** [comment]
ok, thanks again, I will have a try
